name: 'Hello World'
description: 'Test github action'
inputs:
  greeted:
    description: 'who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time greeted'
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.greeted }}
